# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: amazon


variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '0356b4d2-d170-4ac9-8687-07fa8cb8730f'

  # Web app name
  webAppName: 'todo-app'

  # Environment name
  environmentName: 'dev'

  # # Agent VM image name
  # vmImageName: 'ubuntu-latest'

  # ppol

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    # pool:
    #   vmImage: $(vmImageName)

    steps:
    - script: |
        mvn clean package
      displayName: 'Run a multi-line script'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - script: |
        echo $(Build.ArtifactStagingDirectory) 
        cd $(Build.ArtifactStagingDirectory)
        aws s3 cp ./target/*.jar s3://valli-jenkins-s3-bucket/$(Build.BuildNumber)/
      displayName: copy to s3

# - stage: Deploy
#   displayName: Deploy stage
#   dependsOn: Build
#   condition: succeeded()
#   jobs:
#   - deployment: DeployLinuxWebApp
#     displayName: Deploy Linux Web App
#     environment: $(environmentName)
#     pool:
#       vmImage: $(vmImageName)
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - task: AzureWebApp@1
#             displayName: 'Azure Web App Deploy: '
#             inputs:
#               azureSubscription: $(azureSubscription)
#               appType: webAppLinux
#               appName: todo-app111
#               package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
